config/routes.rb
Rails.application.routes.draw do
  resources :jewels
  resources :collections
  
  root 'collections#index'

end

app/models/collection.rb
class Collection < ActiveRecord::Base
    has_many :jewels, dependent: :destroy
end

app/models/jewel.rb
class Jewel < ActiveRecord::Base
  belongs_to :collection
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_collection, only: [:show, :edit, :update, :destroy]

  # GET /collections
  # GET /collections.json
  def index
    @collections = Collection.all
  end

  # GET /collections/1
  # GET /collections/1.json
  def show
    @jewels = Collection.find(params[:id]).jewels
  end

  # GET /collections/new
  def new
    @collection = Collection.new
  end

  # GET /collections/1/edit
  def edit
  end

  # POST /collections
  # POST /collections.json
  def create
    @collection = Collection.new(collection_params)

    respond_to do |format|
      if @collection.save
        format.html { redirect_to @collection, notice: 'Collection was successfully created.' }
        format.json { render :show, status: :created, location: @collection }
      else
        format.html { render :new }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collections/1
  # PATCH/PUT /collections/1.json
  def update
    respond_to do |format|
      if @collection.update(collection_params)
        format.html { redirect_to @collection, notice: 'Collection was successfully updated.' }
        format.json { render :show, status: :ok, location: @collection }
      else
        format.html { render :edit }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collections/1
  # DELETE /collections/1.json
  def destroy
    @collection.destroy
    respond_to do |format|
      format.html { redirect_to collections_url, notice: 'Collection was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collection
      @collection = Collection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def collection_params
      params.require(:collection).permit(:name)
    end
end

app/controllers/jewels_controller.rb
class JewelsController < ApplicationController
  before_action :set_jewel, only: [:show, :edit, :update, :destroy]

  # GET /jewels
  # GET /jewels.json
  def index
    @jewels = Jewel.all
  end

  # GET /jewels/1
  # GET /jewels/1.json
  def show
  end

  # GET /jewels/new
  def new
    @jewel = Jewel.new
  end

  # GET /jewels/1/edit
  def edit
  end
  
  def butts
  end

  # POST /jewels
  # POST /jewels.json
  def create
    @jewel = Jewel.new(jewel_params)

    respond_to do |format|
      if @jewel.save
        format.html { redirect_to @jewel, notice: 'Jewel was successfully created.' }
        format.json { render :show, status: :created, location: @jewel }
      else
        format.html { render :new }
        format.json { render json: @jewel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jewels/1
  # PATCH/PUT /jewels/1.json
  def update
    respond_to do |format|
      
      if @jewel.update(jewel_params)
        format.html { redirect_to collections_path, notice: 'Jewel was successfully purchased.' }
        format.json { render :show, status: :ok, location: @jewel }
      else
        format.html { render :edit }
        format.json { render json: @jewel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jewels/1
  # DELETE /jewels/1.json
  def destroy
    @jewel.destroy
    respond_to do |format|
      format.html { redirect_to jewels_url, notice: 'Jewel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_jewel
      @jewel = Jewel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def jewel_params
      params.require(:jewel).permit(:picture, :description, :price, :available, :collection_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/jewels_helper.rb
module JewelsHelper
end

app/views/collections/_form.html.erb
<%= form_for(@collection) do |f| %>
  <% if @collection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@collection.errors.count, "error") %> prohibited this collection from being saved:</h2>

      <ul>
      <% @collection.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/collections/edit.html.erb
<h1>Editing Collection</h1>

<%= render 'form' %>

<%= link_to 'Show', @collection %> |
<%= link_to 'Back', collections_path %>

app/views/collections/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Le Jewel Stor</h1>

<table>
  <thead>
    <tr>
      <th>Le collections</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @collections.each do |collection| %>
      <tr>
        <td><%= collection.name %></td>
        <td><%= link_to 'Show', collection %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h5><%= link_to 'Add new collection', new_collection_path %></h5>
<h5><%= link_to 'Add new jewel', new_jewel_path %></h5>

app/views/collections/new.html.erb
<h1>New Collection</h1>

<%= render 'form' %>

<%= link_to 'Back', root_url %>

app/views/collections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @collection.name %>
</p>

<div>
    <% if @collection.jewels.any? %>
    
      <h3> <%= @collection.jewels.count %> jewels in collection </h3>
      <%= render @jewels %>
    <% end %>
</div>

<%= link_to 'Edit', edit_collection_path(@collection) %> |
<%= link_to 'Back To Store', collections_path %>

app/views/jewels/_form.html.erb
<%= form_for(@jewel) do |f| %>
  <% if @jewel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@jewel.errors.count, "error") %> prohibited this jewel from being saved:</h2>

      <ul>
      <% @jewel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :picture %><br>
    <%= f.text_field :picture %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :available %><br>
    <%= f.check_box :available %>
  </div>
  <div class="field">
    <%= f.label :collection_id %><br>
    <%= f.text_field :collection_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jewels/_jewel.html.erb
  <%= image_tag jewel.picture %><br />
  <span><%= jewel.description %></span>
  <span>$<%= jewel.price %></span>
  <span>
    <%= form_for(jewel) do |f| %>

      <!--<div class="field">-->
        
        
        
        <% if !jewel.available? %>
        <span>Unavailable</span>
        <% else %>
        <span>Available</span>
        <%= f.hidden_field :available, :value => 'false' %>
        <%= f.submit :Purchase %>
        <% end %>
     <!-- </div>-->
  
      <!--<div class="actions">-->
        
     <!-- </div>-->
  
    <% end %>
  </span>
  <br /><br /><br />

app/views/jewels/edit.html.erb
<h1>Editing Jewel</h1>

<%= render 'form' %>

<%= link_to 'Show', @jewel %> |
<%= link_to 'Back', jewels_path %>

app/views/jewels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Jewels</h1>

<table>
  <thead>
    <tr>
      <th>Picture</th>
      <th>Description</th>
      <th>Price</th>
      <th>Available</th>
      <th>Collection</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jewels.each do |jewel| %>
      <tr>
        <td><%= jewel.picture %></td>
        <td><%= jewel.description %></td>
        <td><%= jewel.price %></td>
        <td><%= jewel.available %></td>
        <td><%= jewel.collection %></td>
        <td><%= link_to 'Show', jewel %></td>
        <td><%= link_to 'Edit', edit_jewel_path(jewel) %></td>
        <td><%= link_to 'Destroy', jewel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Jewel', new_jewel_path %>

app/views/jewels/new.html.erb
<h1>New Jewel</h1>

<%= render 'form' %>

<%= link_to 'Back', root_url %>

app/views/jewels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Picture:</strong>
  <%= @jewel.picture %>
</p>

<p>
  <strong>Description:</strong>
  <%= @jewel.description %>
</p>

<p>
  <strong>Price:</strong>
  $<%= @jewel.price %>
</p>

<p>
  <strong>Available:</strong>
  <%= @jewel.available %>
</p>

<%= link_to 'Edit', edit_jewel_path(@jewel) %> |
<%= link_to 'Back', root_url %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jewelry Store</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<footer>19023 Jewel Street | (540) 274-3071</footer>
</body>
</html>